os:
  - linux

services:
  - docker

before_install:
  - git clone https://github.com/gary1998/Burrow.git && cd Burrow
  - docker build -t gary29198/burrow:latest .
  - docker login -u gary29198 -p 0001221149
  - docker push gary29198/burrow:latest
  - docker pull gary29198/burrow:latest
  - docker run -it gary29198/burrow sh -c run-burrow.sh